In [1]:
import numpy as np

In [2]:
def pi(k, D, j1, N):
    a = len(N)
    J=[j1]
    for i in range(a):
        j_2 = J[i] + N[i]
        J.append(j_2)
    if k == 1:
        k2 = D[-1]
    elif k == D[-1]:
        k2 = 1
    else:
        for i in range(a):
            if (k >= J[i])&(k < J[i] + N[i]):
                j_a = J[i]
                n_a = N[i]
                break
        k2 = 2*j_a + n_a - 1 - k
    return k2

In [3]:
pi(
    4
    , D=[1,2,3,4,5,6]
    , j1 = 2
    , N=[2,2]
)

5

In [4]:
def permutation(l, j1, N):
    D = spisok(l)
    D2 = []
    for el in D:
        D2.append(pi(el, D, j1, N))
    return D, D2

In [5]:
def spisok(l):
    L=[]
    for i in range(1, l+1):
        L.append(i)
    return L

In [6]:
for i in permutation(
    l=7
    , j1=2
    , N=[2,3]):
    print(i)

[1, 2, 3, 4, 5, 6, 7]
[7, 3, 2, 6, 5, 4, 1]


In [7]:
perm = permutation(
    l=7
    , j1=2
    , N=[2,3])

In [8]:
perm

([1, 2, 3, 4, 5, 6, 7], [7, 3, 2, 6, 5, 4, 1])

In [9]:
p = perm[1][:-1]
#p.insert(1, 7)

In [10]:
perm[0][-1]

7

In [11]:
perm[1][:-1].index(perm[0][-1])

0

In [12]:
p

[7, 3, 2, 6, 5, 4]

In [13]:
def move1(perm):
    p = perm[0][:-1]
    i = perm[0][:-1].index(perm[1][-1])
    p.insert(i+1, perm[0][-1])
    return p, perm[1]

In [14]:
def move0(perm):
    p = perm[1][:-1]
    i = perm[1][:-1].index(perm[0][-1])
    p.insert(i+1, perm[1][-1])
    return perm[0], p

In [15]:
def MoveR(perm, path):
    nmove = [int(x) for x in path]
    for i in nmove:
        if i == 0:
            perm = move0(perm)
        if i == 1:
            perm = move1(perm)
    return perm

In [16]:
np.array(
    perm
)

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 3, 2, 6, 5, 4, 1]])

In [17]:
np.array(
    MoveR(perm, '0111000')
)

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 6, 5, 4, 1, 3, 2]])

In [18]:
np.array(move1(move1(move0(perm))))

array([[1, 2, 3, 4, 6, 7, 5],
       [7, 1, 3, 2, 6, 5, 4]])

In [19]:
[int(x) for x in '011000']

[0, 1, 1, 0, 0, 0]

In [20]:
def MMatrix1(perm, Mat=np.eye(3)):
    Mat[perm[1][-1]-1, perm[0][-1]-1] += 1
    return Mat

def MMatrix0(perm, Mat=np.eye(3)):
    Mat[perm[0][-1]-1, perm[1][-1]-1] += 1
    return Mat

def MMatrixN(perm, path, Mat=np.eye(3)):
    nmove = [int(x) for x in path]
    for i in nmove:
        if i == 0:
            Mat = MMatrix0(perm, Mat)
            perm = move0(perm)
        if i == 1:
            Mat = MMatrix1(perm, Mat)
            perm = move1(perm)
    return Mat, perm

def MMatrixR(perm, path, Mat=np.eye(3)):
    nmove = [int(x) for x in path+'9']
    list_path
    for i in range(1,len(nmove)+1):
        list_subpath
        print(i-1, nmove[i-1])
        if nmove[i-1] == nmove[i]:
            li
        
        if nmove[i-1] != nmove[i]:
            
            print('neq')
        


In [21]:
def MMatrixR(perm, path, Mat=np.eye(3)):
    path+='9'
    list_path=[]
    list_subpath=[]
    l=''
    for i in range(1,len(path)):
        l+=path[i-1]
        #print(l)
        #print(path[i])
        if path[i] == '9':
            list_path.append(l)
            
        elif path[i-1] != path[i]:
            list_path.append(l)
            l=''
    #print(list_path)
    Mat_t = Mat.copy()
    for sp in list_path:
        Mat_new, perm = MMatrixN(perm, sp, Mat.copy())
        #print(Mat_t)
        #print(Mat_new)
        Mat_t = Mat_t@Mat_new
    return Mat_t
        
        

In [22]:
MMatrixR(perm, '011000001000', np.eye(7))

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 2., 2., 2., 1.],
       [0., 0., 0., 5., 6., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 1., 1., 1.]])

In [23]:
gamma_0='0'
gamma_1_a='11000001000'
gamma_2_a='111100000100'
gamma_3_c='111111'*8

In [24]:
perm2=MoveR(perm, gamma_0)
perm3=MoveR(perm2, gamma_1_a)
perm4=MoveR(perm3, gamma_2_a)
print(np.array(perm))
print('')
print(np.array(perm2))
print('')
print(np.array(perm3))
print('')
print(np.array(perm4))

[[1 2 3 4 5 6 7]
 [7 3 2 6 5 4 1]]

[[1 2 3 4 5 6 7]
 [7 1 3 2 6 5 4]]

[[1 2 3 4 5 6 7]
 [7 6 5 4 1 3 2]]

[[1 2 3 4 5 6 7]
 [7 3 2 6 5 4 1]]


In [25]:
Delta_0=MMatrixR(perm, gamma_0, np.eye(7))
Delta_1_a=MMatrixR(perm2, gamma_1_a, np.eye(7))
Delta_2_a=MMatrixR(perm3, gamma_2_a, np.eye(7))
Delta_3_c=MMatrixR(perm4, gamma_3_c, np.eye(7))

print(np.array(Delta_0))
print('')
print(np.array(Delta_1_a))
print('')
print(np.array(Delta_2_a))
print('')
print(np.array(Delta_3_c))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 2. 2. 2. 1.]
 [0. 0. 0. 5. 6. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 1. 1. 1. 1.]
 [0. 5. 6. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0. 1.]]

[[1. 8. 8. 8. 8. 8. 8.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [26]:
Delta_0@Delta_1_a@Delta_2_a@Delta_3_c

array([[1., 8., 8., 8., 8., 8., 8.],
       [0., 2., 2., 1., 1., 1., 1.],
       [0., 5., 6., 0., 0., 0., 0.],
       [0., 1., 1., 2., 2., 2., 1.],
       [0., 0., 0., 5., 6., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [1., 9., 9., 9., 9., 9., 9.]])

# perm_6_1

In [27]:
gamma_0='0'
gamma_1_a='11000001000'

In [28]:
p11=[
    [1,2,3,4,5,6],
    [6,5,4,3,2,1]
]

In [29]:
p12=MoveR(p11, gamma_0)
print(np.array(p12))

[[1 2 3 4 5 6]
 [6 1 5 4 3 2]]


In [30]:
D1 = MMatrixR(p11, gamma_0, np.eye(6)) #Delta_gamma_0
D1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [31]:
p13=MoveR(p12, '100'+'1'*5+'011'+'0'*8+'10000')
print(np.array(p13)) #perm_gamma_1_a_b

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


In [32]:
D2 = MMatrixR(p12, '100'+'1'*5+'011'+'0'*8+'10000', np.eye(6)) #Delta_gamma_1_a_b
D2

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  2.,  2.,  2.,  1.],
       [ 0.,  8.,  9.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6.,  5.,  0.],
       [ 0.,  9., 10.,  2.,  2.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.]])

In [33]:
print(np.array(MoveR(p13, '1'*5*11)))

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


In [34]:
D3 = MMatrixR(p13, '1'*5*11, np.eye(6))  #Delta_gamma_3_c
D3

array([[ 1., 11., 11., 11., 11., 11.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [35]:
D1@D2@D3

array([[ 1., 11., 11., 11., 11., 11.],
       [ 0.,  2.,  2.,  2.,  2.,  1.],
       [ 0.,  8.,  9.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6.,  5.,  0.],
       [ 0.,  9., 10.,  2.,  2.,  0.],
       [ 1., 12., 12., 12., 12., 12.]])

# perm_6_2

In [36]:
p21=[
    [1,2,3,4,5,6],
    [6,4,3,2,5,1]
]

In [37]:
p22=MoveR(p21, '0')
print(np.array(p22))

[[1 2 3 4 5 6]
 [6 1 4 3 2 5]]


In [38]:
D21 = MMatrixR(p21, '0', np.eye(6)) #Delta_gamma_0
D21

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [39]:
p23=MoveR(p22, '10')
print(np.array(p23))

[[1 2 3 4 5 6]
 [6 5 1 4 3 2]]


In [40]:
D22 = MMatrixR(p22, '10', np.eye(6)) #Delta_gamma_1
D22

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 2., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [41]:
p24=MoveR(p23, '110'+'1'*6+'011000')
print(np.array(p24))

[[1 2 3 4 5 6]
 [6 4 3 2 5 1]]


In [42]:
D23 = MMatrixR(p23, '110'+'1'*6+'011000', np.eye(6)) #Delta_gamma_2_a
D23

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 2., 2., 1., 1.],
       [0., 0., 7., 6., 0., 0.],
       [0., 1., 2., 2., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 0., 1.]])

In [43]:
p25=MoveR(p24, '1'*5*4)
print(np.array(p25))

[[1 2 3 4 5 6]
 [6 4 3 2 5 1]]


In [44]:
D24 = MMatrixR(p24, '1'*5*4, np.eye(6)) #Delta_gamma_2_a
D24

array([[1., 4., 4., 4., 4., 4.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [45]:
D21@D22@D23@D24

array([[1., 4., 4., 4., 4., 4.],
       [0., 2., 2., 2., 1., 1.],
       [0., 0., 7., 6., 0., 0.],
       [0., 1., 2., 2., 0., 0.],
       [0., 1., 1., 1., 2., 1.],
       [1., 5., 5., 5., 5., 5.]])

# perm 6_3

In [46]:
p31=[
    [1,2,3,4,5,6],
    [6,5,4,3,2,1]
]

In [47]:
p32=MoveR(p31, '0')
print(np.array(p32))

[[1 2 3 4 5 6]
 [6 1 5 4 3 2]]


In [48]:
D31 = MMatrixR(p31, '0', np.eye(6)) #Delta_gamma_0
D31

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [49]:
p33=MoveR(p32, '100'+'1'*5+'011'+'0'*7+'10000')
print(np.array(p33))

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


In [50]:
D32 = MMatrixR(p32, '100'+'1'*3+'011'+'0'*7+'10000', np.eye(6)) #Delta_gamma_1
D32

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 2., 2., 2., 1.],
       [0., 7., 8., 0., 0., 0.],
       [0., 0., 0., 4., 3., 0.],
       [0., 8., 9., 2., 2., 0.],
       [0., 1., 1., 1., 1., 1.]])

In [51]:
p34=MoveR(p33, '1'*5*6)
print(np.array(p34))

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


In [52]:
D33 = MMatrixR(p33, '1'*5*6, np.eye(6)) #Delta_gamma_1
D33

array([[1., 6., 6., 6., 6., 6.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [53]:
D31@D32@D33

array([[1., 6., 6., 6., 6., 6.],
       [0., 2., 2., 2., 2., 1.],
       [0., 7., 8., 0., 0., 0.],
       [0., 0., 0., 4., 3., 0.],
       [0., 8., 9., 2., 2., 0.],
       [1., 7., 7., 7., 7., 7.]])

# perm 7_2

In [54]:
p41=[
    [1,2,3,4,5,6,7],
    [7,4,3,2,5,6,1]
]

In [55]:
p42=MoveR(p41, '0')
print(np.array(p42))

[[1 2 3 4 5 6 7]
 [7 1 4 3 2 5 6]]


In [56]:
D41 = MMatrixR(p41, '0', np.eye(7)) 
D41

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1.]])

In [57]:
p43=MoveR(p42, '10')
print(np.array(p43))

[[1 2 3 4 5 6 7]
 [7 6 1 4 3 2 5]]


In [58]:
D42 = MMatrixR(p42, '10', np.eye(7)) 
D42

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 2., 1.],
       [0., 0., 0., 0., 0., 1., 1.]])

In [59]:
p44=MoveR(p43, '110')
print(np.array(p44))

[[1 2 3 4 5 6 7]
 [7 5 6 1 4 3 2]]


In [60]:
D43 = MMatrixR(p43, '110', np.eye(7)) 
D43

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 2., 1., 1.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 1.]])

In [61]:
p45=MoveR(p44, '1110'+'1'*5+'011000')
print(np.array(p45))

[[1 2 3 4 5 6 7]
 [7 4 3 2 5 6 1]]


In [62]:
D44 = MMatrixR(p44, '1110'+'1'*5+'011000', np.eye(7)) 
D44

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 2., 2., 2., 1., 1., 1.],
       [0., 0., 6., 5., 0., 0., 0.],
       [0., 1., 2., 2., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 0., 0., 1.]])

In [63]:
p46=MoveR(p45, '1'*6*8)
print(np.array(p46))

[[1 2 3 4 5 6 7]
 [7 4 3 2 5 6 1]]


In [64]:
D45 = MMatrixR(p45, '1'*6*8, np.eye(7))
D45

array([[1., 8., 8., 8., 8., 8., 8.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [65]:
D41@D42@D43@D44@D45

array([[1., 8., 8., 8., 8., 8., 8.],
       [0., 2., 2., 2., 1., 1., 1.],
       [0., 0., 6., 5., 0., 0., 0.],
       [0., 1., 2., 2., 0., 0., 0.],
       [0., 1., 1., 1., 2., 1., 1.],
       [0., 1., 1., 1., 1., 2., 1.],
       [1., 9., 9., 9., 9., 9., 9.]])

# perm_N_1

In [96]:
pn1 = permutation(
    l=12
    , j1=2
    , N=[2,2,2,2,2,2])
print(np.array(pn1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  3  2  5  4  7  6  9  8 11 10  1]]


In [97]:
pn2=MoveR(pn1, '0')
print(np.array(pn2))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  1  3  2  5  4  7  6  9  8 11 10]]


In [98]:
Dn1 = MMatrixR(pn1, '0', np.eye(12)) #Delta_gamma_0
Dn1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [99]:
pn3=MoveR(pn2, '1'*1+'0'*5+'100')
print(np.array(pn3))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12 11 10  1  3  2  5  4  7  6  9  8]]


In [100]:
Dn2 = MMatrixR(pn2, '1'*1+'0'*5+'100', np.eye(12))
Dn2

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [103]:
pn4=MoveR(pn3, '1'*3+'0'*5+'100')
print(np.array(pn4))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  9  8 11 10  1  3  2  5  4  7  6]]


In [104]:
Dn3 = MMatrixR(pn3, '1'*3+'0'*5+'100', np.eye(12))
Dn3

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 2., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 5., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.]])

In [105]:
pn5=MoveR(pn4, '1'*5+'0'*5+'100')
print(np.array(pn5))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  7  6  9  8 11 10  1  3  2  5  4]]


In [107]:
Dn4 = MMatrixR(pn4, '1'*5+'0'*5+'100', np.eye(12))
Dn4

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 2., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 5., 6., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.]])

In [108]:
pn6=MoveR(pn5, '1'*7+'0'*5+'100')
print(np.array(pn6))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  5  4  7  6  9  8 11 10  1  3  2]]


In [109]:
Dn5 = MMatrixR(pn5, '1'*7+'0'*5+'100', np.eye(12))
Dn5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 5., 6., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [110]:
pn7=MoveR(pn6, '1'*9+'0'*5+'100')
print(np.array(pn7))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  3  2  5  4  7  6  9  8 11 10  1]]


In [111]:
Dn6 = MMatrixR(pn6, '1'*9+'0'*5+'100', np.eye(12))
Dn6

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 5., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [113]:
pn8=MoveR(pn7, '1'*11*8)
print(np.array(pn8))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [12  3  2  5  4  7  6  9  8 11 10  1]]


In [114]:
Dn7 = MMatrixR(pn7, '1'*11*8, np.eye(12))
Dn7

array([[1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [115]:
Dn1@Dn2@Dn3@Dn4@Dn5@Dn6@Dn7

array([[1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [0., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 5., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 5., 6., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 5., 6., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 5., 6., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 6., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])